### ISSUE TITLE
Empty messages object

### ISSUE THREAD

**Issue by gijs** [intlify/vite-plugin-vue-i18n#68]
Hi!

I'm converting a project from Vue 2 to Vue 3. 

The translation catalogs are in JSON format:

`en.json`:

```json
{
  "key": "Value"
}
```
et cetera... 

## Config files

These are the configurations I'm using:

- vite.config.ts:

```js
import path from "path";
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import vueI18n from "@intlify/vite-plugin-vue-i18n";

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      "vue-i18n": "vue-i18n/dist/vue-i18n.runtime.esm-bundler.js",
    },
  },
  plugins: [
    vue(),
    vueI18n({
      include: path.resolve(__dirname, "./src/locales/"),
    }),
  ],
```

- tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client", "@intlify/vite-plugin-vue-i18n/client"],
    "plugins": [{ "name": "@vuedx/typescript-plugin-vue" }]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}

```

- package.json:

```json
  "dependencies": {
    "vue": "^3.0.5",
    "vue-i18n": "^9.0.0-rc.7"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^2.0.0-rc.2",
    "@types/node": "^14.14.31",
    "@vitejs/plugin-vue": "^1.1.4",
    "@vue/compiler-sfc": "^3.0.5",
    "@vuedx/typecheck": "^0.6.0",
    "@vuedx/typescript-plugin-vue": "^0.6.3",
    "autoprefixer": "^10.2.4",
    "postcss": "^8.2.6",
    "tailwindcss": "^2.0.3",
    "typescript": "^4.1.3",
    "vite": "^2.0.0"
  }
```

## Code

- main.ts:

```ts
import { createApp } from "vue";
import { createI18n } from "vue-i18n";
import App from "./App.vue";
import "./index.css";
import messages from "@intlify/vite-plugin-vue-i18n/messages";

console.log("messages:", messages);

const i18n = createI18n({
  locale: "en",
  messages
});

createApp(App).use(i18n).mount("#app");

```

- App.vue:

```vue
<template>
  <form>
    <select v-model="locale">
      <option value="en">en</option>
      <option value="nl">nl</option>
    </select>
  </form>
  test: {{ t("General_Ok") }}
  <HelloWorld msg="Hello Vue 3 + TypeScript + Vite" />
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useI18n } from "vue-i18n";
import HelloWorld from "./components/HelloWorld.vue";

export default defineComponent({
  name: "App",
  components: {
    HelloWorld,
  },
  setup() {
    const { locale, t } = useI18n({
      inheritLocale: true,
    });
    return { locale, t };
  },
});
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

```

## Console output

![Screenshot 2021-02-22 at 20 40 49](https://user-images.githubusercontent.com/7193/108760750-52ae8500-754e-11eb-9861-6cdd368b4c8a.png)

## Other stuff

- The url `http://localhost:3000/@id/@intlify/vite-plugin-vue-i18n/messages` gives:
```
export default {
  
}
```

- If I replace the `path.resolve()` in `vite.config.js` with a string path to the locales directory, it doesn't work either...

Not sure what I'm missing... probably something small :) 

Can you/anyone help me out?

Thanks a lot!

**Comment by kazupon** [comment]
I realized it's local scope in App.vue

```js
setup() {
    const { locale, t } = useI18n({
      inheritLocale: true,
    });
    return { locale, t };
  },
```

You need to define locale messages with `useI18n` or `<i18n> custom block`


> * The url `http://localhost:3000/@id/@intlify/vite-plugin-vue-i18n/messages` gives:
> 
> ```
> export default {
>   
> }
> ```

This is strange… 🤔  it works fine with vite-vue-i18n-starter.

Could you provide repro minimu repo, please?

**Comment by gijs** [comment]
Yes I will create a repro repo for this...

I just cloned `vite-vue-i18n-starter`, which worked indeed.
When I copy `en.json` to `nl.json`, add NL to the dropdown, and change the translation to Dutch, it still works...

But when I add my own translation catalog as nl.json, it fails:
```
11:22:52 [vite] Internal server error: Cannot read property 'message' of undefined
      at Object.newOptions.onError (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/cli/lib/src/generator/codegen.js:102:48)
      at Object.newOptions.onError (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/cli/lib/src/generator/codegen.js:102:36)
      at newOptions.onError (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/cli/lib/src/generator/codegen.js:102:36)
      at emitError (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:175:13)
      at readTokenInLinked (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:726:21)
      at readToken (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:740:20)
      at Object.nextToken (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:782:16)
      at parseLinked (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:917:31)
      at parseMessage (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1016:36)
      at parseResource (/Users/gijs/Projects/oa-admin-platform-client/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1055:25) (x3)
```

**Comment by gijs** [comment]
Well, the message-compiler seems to be the culprit.
It crashes on all sorts of symbols I have in the messages catalog (`{`, `}`, `<`, etc... )
Not sure how to appoach this...
